#### Librerias

In [1]:
import pandas as pd
import numpy as np
import os

#### Parametros

In [21]:
#PATH = 'C:/Users/tinch/coderhouse/template/data/raw/'


PATH_PROJECT = 'C:/Users/vatec/OneDrive/Documentos/Hans/Cursos/5 CODERHOUSE - Data Science II - Machine Learning para la Ciencia de Datos Flex/Material/Proyectos/Template Model Project DS/'

PATH = PATH_PROJECT +'data/raw/'

#### Lectura de archivos

In [4]:
cardio = pd.read_excel(f'{PATH}cardio.xlsx')

In [37]:
cardio

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667
3,3,4.166667,2.500000,13.416667,10.583333,1.875000,9.416667
4,4,5.000000,3.083333,7.666667,3.083333,2.583333,4.458333
...,...,...,...,...,...,...,...
49995,27343,NaN,NaN,NaN,NaN,2.625000,3.041667
49996,27350,NaN,NaN,NaN,NaN,2.250000,3.208333
49997,27351,NaN,NaN,NaN,NaN,1.958333,2.208333
49998,27352,NaN,NaN,NaN,NaN,2.583333,4.125000
49999,27354,NaN,NaN,NaN,NaN,2.750000,5.041667

In [5]:
fisicas = pd.read_excel(f'{PATH}fisicas.xlsx')

In [15]:
fisicas

          ID gender   age  height(cm)  weight(kg)  waist(cm)
0          0      F  40.0       155.0        60.0   3.377083
1          1      F  40.0       160.0        60.0   3.375000
2          2      M  55.0       170.0        60.0   3.333333
3          3      M  40.0       165.0        70.0   3.666667
4          4      F  40.0       155.0        60.0   3.583333
...      ...    ...   ...         ...         ...        ...
49995  27343      M  50.0       160.0        55.0   2.961806
49996  27350      M  30.0       170.0        70.0   3.333333
49997  27351      M  20.0       165.0        65.0   3.541667
49998  27352      F  60.0       160.0        45.0   2.961806
49999  27354      M  45.0       170.0        80.0   4.000000

[50000 rows x 6 columns]

In [6]:
metabolicas = pd.read_excel(f'{PATH}metabolicas.xlsx')

In [17]:
metabolicas

,ID,fasting blood sugar,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp
0,0,3.916667,0.506250,0.041667,0.004861,0.750000,0.791667,1.125000
1,1,5.416667,0.504861,0.041667,0.004167,0.916667,0.791667,0.750000
2,2,3.708333,0.630556,0.041667,0.041667,0.875000,0.666667,0.916667
3,3,4.000000,0.588194,0.041667,0.041667,0.791667,1.083333,0.750000
4,4,3.333333,0.503472,0.041667,0.004167,0.666667,0.583333,0.916667
...,...,...,...,...,...,...,...,...
49995,27343,4.125000,0.547917,0.041667,NaN,NaN,NaN,0.916667
49996,27350,3.708333,0.629167,0.041667,NaN,NaN,NaN,0.750000
49997,27351,3.958333,0.670833,0.041667,NaN,NaN,NaN,2.916667
49998,27352,3.916667,0.584028,0.041667,NaN,NaN,NaN,1.041667
49999,27354,4.166667,0.625000,0.041667,NaN,NaN,NaN,2.583333

In [7]:
oral = pd.read_excel(f'{PATH}oral.xlsx')

In [18]:
oral

          ID oral  dental caries tartar
0          0    Y              0      Y
1          1    Y              0      Y
2          2    Y              0      N
3          3    Y              0      Y
4          4    Y              0      N
...      ...  ...            ...    ...
49995  27343    Y              0      Y
49996  27350    Y              1      Y
49997  27351    Y              0      Y
49998  27352    Y              1      Y
49999  27354    Y              1      N

[50000 rows x 4 columns]

In [8]:
sentidos = pd.read_excel(f'{PATH}sentidos.xlsx')

In [11]:
sentidos

          ID  eyesight(left)  eyesight(right)  hearing(left)  hearing(right)
0          0        0.043056         0.041667       0.041667        0.041667
1          1        0.005556         0.004167       0.041667        0.041667
2          2        0.005556         0.005556       0.041667        0.041667
3          3        0.045139         0.045139       0.041667        0.041667
4          4        0.041667         0.041667       0.041667        0.041667
...      ...             ...              ...            ...             ...
49995  27343        0.004861         0.005556       0.041667             NaN
49996  27350        0.045139         0.041667       0.041667             NaN
49997  27351        0.045139         0.045139       0.041667             NaN
49998  27352        0.002778         0.002778       0.041667             NaN
49999  27354        0.045139         0.041667       0.041667             NaN

[50000 rows x 5 columns]

In [9]:
target = pd.read_excel(f'{PATH}target.xlsx')

In [10]:
target

          ID  target
0          0       0
1          1       0
2          2       1
3          3       0
4          4       0
...      ...     ...
49995  27343       1
49996  27350       1
49997  27351       1
49998  27352       0
49999  27354       1

[50000 rows x 2 columns]

In [12]:
df = pd.merge(cardio, fisicas, on="ID", how="left")

In [13]:
df = pd.merge(df, metabolicas, on="ID", how="left")

In [14]:
df = pd.merge(df, oral, on="ID", how="left")

In [16]:
df = pd.merge(df, sentidos, on="ID", how="left")

In [17]:
df = pd.merge(df, target, on="ID", how="left")

In [18]:
df

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,gender,age,height(cm),...,tartar,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,F,40.0,155.0,...,Y,0.043056,0.041667,0.041667,0.041667,0.043056,0.041667,0.041667,0.041667,0
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,F,40.0,160.0,...,Y,0.005556,0.004167,0.041667,0.041667,0.005556,0.004167,0.041667,0.041667,0
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,M,55.0,170.0,...,N,0.005556,0.005556,0.041667,0.041667,0.005556,0.005556,0.041667,0.041667,1
3,3,4.166667,2.500000,13.416667,10.583333,1.875000,9.416667,M,40.0,165.0,...,Y,0.045139,0.045139,0.041667,0.041667,0.045139,0.045139,0.041667,0.041667,0
4,4,5.000000,3.083333,7.666667,3.083333,2.583333,4.458333,F,40.0,155.0,...,N,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,27343,NaN,NaN,NaN,NaN,2.625000,3.041667,M,50.0,160.0,...,Y,0.004861,0.005556,0.041667,NaN,0.004861,0.005556,0.041667,NaN,1
49996,27350,NaN,NaN,NaN,NaN,2.250000,3.208333,M,30.0,170.0,...,Y,0.045139,0.041667,0.041667,NaN,0.045139,0.041667,0.041667,NaN,1
49997,27351,NaN,NaN,NaN,NaN,1.958333,2.208333,M,20.0,165.0,...,Y,0.045139,0.045139,0.041667,NaN,0.045139,0.045139,0.041667,NaN,1
49998,27352,NaN,NaN,NaN,NaN,2.583333,4.125000,F,60.0,160.0,...,Y,0.002778,0.002778,0.041667,NaN,0.002778,0.002778,0.041667,NaN,0
49999,27354,NaN,NaN,NaN,NaN,2.750000,5.041667,M,45.0,170.0,...,N,0.045139,0.041667,0.041667,NaN,0.045139,0.041667,0.041667,NaN,1

In [22]:
df.to_csv(PATH_PROJECT + "data/processed/dataset_merged.csv", index=False)