In [1]:
import pandas as pd

# ONE-HOT-ENCODING: para variables categoricas nominales (bien)
# ONE-HOT-ENCODING: para variables categoricas ordinales (bien, pero se pierde la "jerarquia" u "orden")

# LABEL ENCODING: para variables categoricas ordinales (bien), el unico problema es definir los "valores" de las clases.
# LABEL ENCODING:: para variables categoricas nominales (pesimo), se va a sesgar y un modelo podria interpretar una jerarquia/orden donde no existe.

In [2]:
PATH_PROJECT = 'C:/Users/vatec/OneDrive/Documentos/Hans/Cursos/5 CODERHOUSE - Data Science II - Machine Learning para la Ciencia de Datos Flex/Material/Proyectos/Template Model Project DS/'


PATH = PATH_PROJECT +'data/processed/'

In [3]:

df = pd.read_csv(f'{PATH}dataset_merged_processed_eda.csv')

In [4]:
df_copy = df.copy()
df_copy_2 = df.copy()

Opcion 1)

In [5]:
df

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,gender,age,height(cm),...,tartar,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,F,40.0,155.0,...,Y,0.043056,0.041667,0.041667,0.041667,0.043056,0.041667,0.041667,0.041667,0
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,F,40.0,160.0,...,Y,0.005556,0.004167,0.041667,0.041667,0.005556,0.004167,0.041667,0.041667,0
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,M,55.0,170.0,...,N,0.005556,0.005556,0.041667,0.041667,0.005556,0.005556,0.041667,0.041667,1
3,3,4.166667,2.500000,13.416667,10.583333,1.875000,9.416667,M,40.0,165.0,...,Y,0.045139,0.045139,0.041667,0.041667,0.045139,0.045139,0.041667,0.041667,0
4,4,5.000000,3.083333,7.666667,3.083333,2.583333,4.458333,F,40.0,155.0,...,N,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,27343,5.062688,3.167519,8.206039,5.275309,2.625000,3.041667,M,50.0,160.0,...,Y,0.004861,0.005556,0.041667,0.042758,0.004861,0.005556,0.041667,0.042758,1
49996,27350,5.062688,3.167519,8.206039,5.275309,2.250000,3.208333,M,30.0,170.0,...,Y,0.045139,0.041667,0.041667,0.042758,0.045139,0.041667,0.041667,0.042758,1
49997,27351,5.062688,3.167519,8.206039,5.275309,1.958333,2.208333,M,20.0,165.0,...,Y,0.045139,0.045139,0.041667,0.042758,0.045139,0.045139,0.041667,0.042758,1
49998,27352,5.062688,3.167519,8.206039,5.275309,2.583333,4.125000,F,60.0,160.0,...,Y,0.002778,0.002778,0.041667,0.042758,0.002778,0.002778,0.041667,0.042758,0
49999,27354,5.062688,3.167519,8.206039,5.275309,2.750000,5.041667,M,45.0,170.0,...,N,0.045139,0.041667,0.041667,0.042758,0.045139,0.041667,0.041667,0.042758,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   systolic             50000 non-null  float64
 2   relaxation           50000 non-null  float64
 3   Cholesterol          50000 non-null  float64
 4   triglyceride         50000 non-null  float64
 5   HDL                  50000 non-null  float64
 6   LDL                  50000 non-null  float64
 7   gender               50000 non-null  str
 8   age                  50000 non-null  float64
 9   height(cm)           50000 non-null  float64
 10  weight(kg)           50000 non-null  float64
 11  waist(cm)            50000 non-null  float64
 12  fasting blood sugar  50000 non-null  float64
 13  hemoglobin           50000 non-null  float64
 14  Urine protein        50000 non-null  float64
 15  serum creatinine     50000 non-null  float64
 16  ALT                  50000 non-null  float64
 17  Gtp                  50000 non-null  float64
 18  dental caries        50000 non-null  int64
 19  tartar               50000 non-null  str
 20  eyesight(left)_x     50000 non-null  float64
 21  eyesight(right)_x    50000 non-null  float64
 22  hearing(left)_x      50000 non-null  float64
 23  hearing(right)_x     50000 non-null  float64
 24  eyesight(left)_y     50000 non-null  float64
 25  eyesight(right)_y    50000 non-null  float64
 26  hearing(left)_y      50000 non-null  float64
 27  hearing(right)_y     50000 non-null  float64
 28  target               50000 non-null  int64
dtypes: float64(24), int64(3), str(2)
memory usage: 11.1 MB

In [7]:
df.gender.nunique()

2

In [8]:
df.tartar.unique()

<StringArray>
['Y', 'N']
Length: 2, dtype: str

In [9]:
df["gender"] = df["gender"].map({"F": 0, "M": 1})

In [10]:
df["tartar"] = df["tartar"].map({"N": 0, "Y": 1})

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   systolic             50000 non-null  float64
 2   relaxation           50000 non-null  float64
 3   Cholesterol          50000 non-null  float64
 4   triglyceride         50000 non-null  float64
 5   HDL                  50000 non-null  float64
 6   LDL                  50000 non-null  float64
 7   gender               50000 non-null  int64
 8   age                  50000 non-null  float64
 9   height(cm)           50000 non-null  float64
 10  weight(kg)           50000 non-null  float64
 11  waist(cm)            50000 non-null  float64
 12  fasting blood sugar  50000 non-null  float64
 13  hemoglobin           50000 non-null  float64
 14  Urine protein        50000 non-null  float64
 15  serum creatinine     50000 non-null  float64
 16  ALT                  50000 non-null  float64
 17  Gtp                  50000 non-null  float64
 18  dental caries        50000 non-null  int64
 19  tartar               50000 non-null  int64
 20  eyesight(left)_x     50000 non-null  float64
 21  eyesight(right)_x    50000 non-null  float64
 22  hearing(left)_x      50000 non-null  float64
 23  hearing(right)_x     50000 non-null  float64
 24  eyesight(left)_y     50000 non-null  float64
 25  eyesight(right)_y    50000 non-null  float64
 26  hearing(left)_y      50000 non-null  float64
 27  hearing(right)_y     50000 non-null  float64
 28  target               50000 non-null  int64
dtypes: float64(24), int64(5)
memory usage: 11.1 MB

Opcion 2)

In [12]:
df_op_2 = pd.get_dummies(df_copy, columns=["gender", "tartar"], drop_first=True)

In [13]:
df_op_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   systolic             50000 non-null  float64
 2   relaxation           50000 non-null  float64
 3   Cholesterol          50000 non-null  float64
 4   triglyceride         50000 non-null  float64
 5   HDL                  50000 non-null  float64
 6   LDL                  50000 non-null  float64
 7   age                  50000 non-null  float64
 8   height(cm)           50000 non-null  float64
 9   weight(kg)           50000 non-null  float64
 10  waist(cm)            50000 non-null  float64
 11  fasting blood sugar  50000 non-null  float64
 12  hemoglobin           50000 non-null  float64
 13  Urine protein        50000 non-null  float64
 14  serum creatinine     50000 non-null  float64
 15  ALT                  50000 non-null  float64
 16  Gtp                  50000 non-null  float64
 17  dental caries        50000 non-null  int64
 18  eyesight(left)_x     50000 non-null  float64
 19  eyesight(right)_x    50000 non-null  float64
 20  hearing(left)_x      50000 non-null  float64
 21  hearing(right)_x     50000 non-null  float64
 22  eyesight(left)_y     50000 non-null  float64
 23  eyesight(right)_y    50000 non-null  float64
 24  hearing(left)_y      50000 non-null  float64
 25  hearing(right)_y     50000 non-null  float64
 26  target               50000 non-null  int64
 27  gender_M             50000 non-null  bool
 28  tartar_Y             50000 non-null  bool
dtypes: bool(2), float64(24), int64(3)
memory usage: 10.4 MB

In [14]:
# df_op_2["gender_F"] = df_op_2["gender_F"].astype(int)
df_op_2["gender_M"] = df_op_2["gender_M"].astype(int)
# df_op_2["tartar_N"] = df_op_2["tartar_N"].astype(int)
df_op_2["tartar_Y"] = df_op_2["tartar_Y"].astype(int)

In [15]:
df_op_2

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,age,height(cm),weight(kg),...,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target,gender_M,tartar_Y
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,40.0,155.0,60.0,...,0.041667,0.041667,0.041667,0.043056,0.041667,0.041667,0.041667,0,0,1
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,40.0,160.0,60.0,...,0.004167,0.041667,0.041667,0.005556,0.004167,0.041667,0.041667,0,0,1
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,55.0,170.0,60.0,...,0.005556,0.041667,0.041667,0.005556,0.005556,0.041667,0.041667,1,1,0
3,3,4.166667,2.500000,13.416667,10.583333,1.875000,9.416667,40.0,165.0,70.0,...,0.045139,0.041667,0.041667,0.045139,0.045139,0.041667,0.041667,0,1,1
4,4,5.000000,3.083333,7.666667,3.083333,2.583333,4.458333,40.0,155.0,60.0,...,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,27343,5.062688,3.167519,8.206039,5.275309,2.625000,3.041667,50.0,160.0,55.0,...,0.005556,0.041667,0.042758,0.004861,0.005556,0.041667,0.042758,1,1,1
49996,27350,5.062688,3.167519,8.206039,5.275309,2.250000,3.208333,30.0,170.0,70.0,...,0.041667,0.041667,0.042758,0.045139,0.041667,0.041667,0.042758,1,1,1
49997,27351,5.062688,3.167519,8.206039,5.275309,1.958333,2.208333,20.0,165.0,65.0,...,0.045139,0.041667,0.042758,0.045139,0.045139,0.041667,0.042758,1,1,1
49998,27352,5.062688,3.167519,8.206039,5.275309,2.583333,4.125000,60.0,160.0,45.0,...,0.002778,0.041667,0.042758,0.002778,0.002778,0.041667,0.042758,0,0,1
49999,27354,5.062688,3.167519,8.206039,5.275309,2.750000,5.041667,45.0,170.0,80.0,...,0.041667,0.041667,0.042758,0.045139,0.041667,0.041667,0.042758,1,1,0

In [19]:

df_op_2.to_csv(PATH + "dataset_merged_processed_cod.csv", index=False)

Opcion 3) "Teorica"

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(handle_unknown = "Ignore") # si el dia de mañana, las variables categoricas pueden o van a tener valores nuevos desconocidos al momento de entrenar, usar "handle_unknown=.."

In [ ]:
# para entrenar el ohe, debemos usar X_train (SIEMPRE CON .FIT() DEBEN USAR EL CONJUNTO DE ENTRENAMIENTO")

In [18]:
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  OneHotEncoder(
 |      *,
 |      categories='auto',
 |      drop=None,
 |      sparse_output=True,
 |      dtype=<class 'numpy.float64'>,
 |      handle_unknown='error',
 |      min_frequency=None,
 |      max_categories=None,
 |      feature_name_combiner='concat'
 |  )
 |
 |  Encode categorical features as a one-hot numeric array.
 |
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse_output``
 |  parameter).
 |
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard kernels.
 |
 |  Note: a one-hot encoding of y labels should use a LabelBinarizer
 |  instead.
 |
 |  Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
 |  For a comparison of different encoders, refer to:
 |  :ref:`sphx_glr_auto_examples_preprocessing_plot_target_encoder.py`.
 |
 |  Parameters
 |  ----------
 |  categories : 'auto' or a list of array-like, default='auto'
 |      Categories (unique values) per feature:
 |
 |      - 'auto' : Determine categories automatically from the training data.
 |      - list : ``categories[i]`` holds the categories expected in the ith
 |        column. The passed categories should not mix strings and numeric
 |        values within a single feature, and should be sorted in case of
 |        numeric values.
 |
 |      The used categories can be found in the ``categories_`` attribute.
 |
 |      .. versionadded:: 0.20
 |
 |  drop : {'first', 'if_binary'} or an array-like of shape (n_features,),             default=None
 |      Specifies a methodology to use to drop one of the categories per
 |      feature. This is useful in situations where perfectly collinear
 |      features cause problems, such as when feeding the resulting data
 |      into an unregularized linear regression model.
 |
 |      However, dropping one category breaks the symmetry of the original
 |      representation and can therefore induce a bias in downstream models,
 |      for instance for penalized linear classification or regression models.
 |
 |      - None : retain all features (the default).
 |      - 'first' : drop the first category in each feature. If only one
 |        category is present, the feature will be dropped entirely.
 |      - 'if_binary' : drop the first category in each feature with two
 |        categories. Features with 1 or more than 2 categories are
 |        left intact.
 |      - array : ``drop[i]`` is the category in feature ``X[:, i]`` that
 |        should be dropped.
 |
 |      When `max_categories` or `min_frequency` is configured to group
 |      infrequent categories, the dropping behavior is handled after the
 |      grouping.
 |
 |      .. versionadded:: 0.21
 |         The parameter `drop` was added in 0.21.
 |
 |      .. versionchanged:: 0.23
 |         The option `drop='if_binary'` was added in 0.23.
 |
 |      .. versionchanged:: 1.1
 |          Support for dropping infrequent categories.
 |
 |  sparse_output : bool, default=True
 |      When ``True``, it returns a :class:`scipy.sparse.csr_matrix`,
 |      i.e. a sparse matrix in "Compressed Sparse Row" (CSR) format.
 |
 |      .. versionadded:: 1.2
 |         `sparse` was renamed to `sparse_output`
 |
 |  dtype : number type, default=np.float64
 |      Desired dtype of output.
 |
 |  handle_unknown : {'error', 'ignore', 'infrequent_if_exist', 'warn'},                      default='error'
 |      Specifies the way unknown categories are handled during :meth:`transform`.
 |
 |      - 'error' : Raise an error if an unknown category is present during transform.
 |      - 'ignore' : When an unknown category is encountered during
 |        transform, the resulting one-hot encoded columns for this feature
 |        will be all zeros. In the inverse transform, an unknown category
 |        will be denoted as None.
 |      - 'infrequent_if_exist' : When an unknown category is encountered
 |        during transform, the resulting one-hot encoded columns for this
 |        feature will map to the infrequent category if it exists. The
 |        infrequent category will be mapped to the last position in the
 |        encoding. During inverse transform, an unknown category will be
 |        mapped to the category denoted `'infrequent'` if it exists. If the
 |        `'infrequent'` category does not exist, then :meth:`transform` and
 |        :meth:`inverse_transform` will handle an unknown category as with
 |        `handle_unknown='ignore'`. Infrequent categories exist based on
 |        `min_frequency` and `max_categories`. Read more in the
 |        :ref:`User Guide <encoder_infrequent_categories>`.
 |      - 'warn' : When an unknown category is encountered during transform
 |        a warning is issued, and the encoding then proceeds as described for
 |        `handle_unknown="infrequent_if_exist"`.
 |
 |      .. versionchanged:: 1.1
 |          `'infrequent_if_exist'` was added to automatically handle unknown
 |          categories and infrequent categories.
 |
 |      .. versionadded:: 1.6
 |         The option `"warn"` was added in 1.6.
 |
 |  min_frequency : int or float, default=None
 |      Specifies the minimum frequency below which a category will be
 |      considered infrequent.
 |
 |      - If `int`, categories with a smaller cardinality will be considered
 |        infrequent.
 |
 |      - If `float`, categories with a smaller cardinality than
 |        `min_frequency * n_samples`  will be considered infrequent.
 |
 |      .. versionadded:: 1.1
 |          Read more in the :ref:`User Guide <encoder_infrequent_categories>`.
 |
 |  max_categories : int, default=None
 |      Specifies an upper limit to the number of output features for each input
 |      feature when considering infrequent categories. If there are infrequent
 |      categories, `max_categories` includes the category representing the
 |      infrequent categories along with the frequent categories. If `None`,
 |      there is no limit to the number of output features.
 |
 |      .. versionadded:: 1.1
 |          Read more in the :ref:`User Guide <encoder_infrequent_categories>`.
 |
 |  feature_name_combiner : "concat" or callable, default="concat"
 |      Callable with signature `def callable(input_feature, category)` that returns a
 |      string. This is used to create feature names to be returned by
 |      :meth:`get_feature_names_out`.
 |
 |      `"concat"` concatenates encoded feature name and category with
 |      `feature + "_" + str(category)`.E.g. feature X with values 1, 6, 7 create
 |      feature names `X_1, X_6, X_7`.
 |
 |      .. versionadded:: 1.3
 |
 |  Attributes
 |  ----------
 |  categories_ : list of arrays
 |      The categories of each feature determined during fitting
 |      (in order of the features in X and corresponding with the output
 |      of ``transform``). This includes the category specified in ``drop``
 |      (if any).
 |
 |  drop_idx_ : array of shape (n_features,)
 |      - ``drop_idx_[i]`` is the index in ``categories_[i]`` of the category
 |        to be dropped for each feature.
 |      - ``drop_idx_[i] = None`` if no category is to be dropped from the
 |        feature with index ``i``, e.g. when `drop='if_binary'` and the
 |        feature isn't binary.
 |      - ``drop_idx_ = None`` if all the transformed features will be
 |        retained.
 |
 |      If infrequent categories are enabled by setting `min_frequency` or
 |      `max_categories` to a non-default value and `drop_idx[i]` corresponds
 |      to an infrequent category, then the entire infrequent category is
 |      dropped.
 |
 |      .. versionchanged:: 0.23
 |         Added the possibility to contain `None` values.
 |
 |  infrequent_categories_ : list of ndarray
 |      Defined only if infrequent categories are enabled by setting
 |      `min_frequency` or `max_categories` to a non-default value.
 |      `infrequent_categories_[i]` are the infrequent categories for feature
 |      `i`. If the feature `i` has no infrequent categories
 |      `infrequent_categories_[i]` is None.
 |
 |      .. versionadded:: 1.1
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 1.0
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  feature_name_combiner : callable or None
 |      Callable with signature `def callable(input_feature, category)` that returns a
 |      string. This is used to create feature names to be returned by
 |      :meth:`get_feature_names_out`.
 |
 |      .. versionadded:: 1.3
 |
 |  See Also
 |  --------
 |  OrdinalEncoder : Performs an ordinal (integer)
 |    encoding of the categorical features.
 |  TargetEncoder : Encodes categorical features using the target.
 |  sklearn.feature_extraction.DictVectorizer : Performs a one-hot encoding of
 |    dictionary items (also handles string-valued features).
 |  sklearn.feature_extraction.FeatureHasher : Performs an approximate one-hot
 |    encoding of dictionary items or strings.
 |  LabelBinarizer : Binarizes labels in a one-vs-all
 |    fashion.
 |  MultiLabelBinarizer : Transforms between iterable of
 |    iterables and a multilabel format, e.g. a (samples x classes) binary
 |    matrix indicating the presence of a class label.
 |
 |  Examples
 |  --------
 |  Given a dataset with two features, we let the encoder find the unique
 |  values per feature and transform the data to a binary one-hot encoding.
 |
 |  >>> from sklearn.preprocessing import OneHotEncoder
 |
 |  One can discard categories not seen during `fit`:
 |
 |  >>> enc = OneHotEncoder(handle_unknown='ignore')
 |  >>> X = [['Male', 1], ['Female', 3], ['Female', 2]]
 |  >>> enc.fit(X)
 |  OneHotEncoder(handle_unknown='ignore')
 |  >>> enc.categories_
 |  [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
 |  >>> enc.transform([['Female', 1], ['Male', 4]]).toarray()
 |  array([[1., 0., 1., 0., 0.],
 |         [0., 1., 0., 0., 0.]])
 |  >>> enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
 |  array([['Male', 1],
 |         [None, 2]], dtype=object)
 |  >>> enc.get_feature_names_out(['gender', 'group'])
 |  array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'], ...)
 |
 |  One can always drop the first column for each feature:
 |
 |  >>> drop_enc = OneHotEncoder(drop='first').fit(X)
 |  >>> drop_enc.categories_
 |  [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
 |  >>> drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()
 |  array([[0., 0., 0.],
 |         [1., 1., 0.]])
 |
 |  Or drop a column for feature only having 2 categories:
 |
 |  >>> drop_binary_enc = OneHotEncoder(drop='if_binary').fit(X)
 |  >>> drop_binary_enc.transform([['Female', 1], ['Male', 2]]).toarray()
 |  array([[0., 1., 0., 0.],
 |         [1., 0., 1., 0.]])
 |
 |  One can change the way feature names are created.
 |
 |  >>> def custom_combiner(feature, category):
 |  ...     return str(feature) + "_" + type(category).__name__ + "_" + str(category)
 |  >>> custom_fnames_enc = OneHotEncoder(feature_name_combiner=custom_combiner).fit(X)
 |  >>> custom_fnames_enc.get_feature_names_out()
 |  array(['x0_str_Female', 'x0_str_Male', 'x1_int_1', 'x1_int_2', 'x1_int_3'],
 |        dtype=object)
 |
 |  Infrequent categories are enabled by setting `max_categories` or `min_frequency`.
 |
 |  >>> import numpy as np
 |  >>> X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
 |  >>> ohe = OneHotEncoder(max_categories=3, sparse_output=False).fit(X)
 |  >>> ohe.infrequent_categories_
 |  [array(['a', 'd'], dtype=object)]
 |  >>> ohe.transform([["a"], ["b"]])
 |  array([[0., 0., 1.],
 |         [1., 0., 0.]])
 |
 |  Method resolution order:
 |      OneHotEncoder
 |      _BaseEncoder
 |      sklearn.base.TransformerMixin
 |      sklearn.utils._set_output._SetOutputMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._repr_html.base.ReprHTMLMixin
 |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(
 |      self,
 |      *,
 |      categories='auto',
 |      drop=None,
 |      sparse_output=True,
 |      dtype=<class 'numpy.float64'>,
 |      handle_unknown='error',
 |      min_frequency=None,
 |      max_categories=None,
 |      feature_name_combiner='concat'
 |  )
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y=None)
 |      Fit OneHotEncoder to X.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          The data to determine the categories of each feature.
 |
 |      y : None
 |          Ignored. This parameter exists only for compatibility with
 |          :class:`~sklearn.pipeline.Pipeline`.
 |
 |      Returns
 |      -------
 |      self
 |          Fitted encoder.
 |
 |  get_feature_names_out(self, input_features=None)
 |      Get output feature names for transformation.
 |
 |      Parameters
 |      ----------
 |      input_features : array-like of str or None, default=None
 |          Input features.
 |
 |          - If `input_features` is `None`, then `feature_names_in_` is
 |            used as feature names in. If `feature_names_in_` is not defined,
 |            then the following input feature names are generated:
 |            `["x0", "x1", ..., "x(n_features_in_ - 1)"]`.
 |          - If `input_features` is an array-like, then `input_features` must
 |            match `feature_names_in_` if `feature_names_in_` is defined.
 |
 |      Returns
 |      -------
 |      feature_names_out : ndarray of str objects
 |          Transformed feature names.
 |
 |  inverse_transform(self, X)
 |      Convert the data back to the original representation.
 |
 |      When unknown categories are encountered (all zeros in the
 |      one-hot encoding), ``None`` is used to represent this category. If the
 |      feature with the unknown category has a dropped category, the dropped
 |      category will be its inverse.
 |
 |      For a given input feature, if there is an infrequent category,
 |      'infrequent_sklearn' will be used to represent the infrequent category.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape                 (n_samples, n_encoded_features)
 |          The transformed data.
 |
 |      Returns
 |      -------
 |      X_original : ndarray of shape (n_samples, n_features)
 |          Inverse transformed array.
 |
 |  transform(self, X)
 |      Transform X using one-hot encoding.
 |
 |      If `sparse_output=True` (default), it returns an instance of
 |      :class:`scipy.sparse._csr.csr_matrix` (CSR format).
 |
 |      If there are infrequent categories for a feature, set by specifying
 |      `max_categories` or `min_frequency`, the infrequent categories are
 |      grouped into a single category.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          The data to encode.
 |
 |      Returns
 |      -------
 |      X_out : {ndarray, sparse matrix} of shape                 (n_samples, n_encoded_features)
 |          Transformed input. If `sparse_output=True`, a sparse matrix will be
 |          returned.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _BaseEncoder:
 |
 |  __sklearn_tags__(self)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from _BaseEncoder:
 |
 |  infrequent_categories_
 |      Infrequent categories for each feature.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.TransformerMixin:
 |
 |  fit_transform(self, X, y=None, **fit_params)
 |      Fit to data, then transform it.
 |
 |      Fits transformer to `X` and `y` with optional parameters `fit_params`
 |      and returns a transformed version of `X`.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Input samples.
 |
 |      y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
 |          Target values (None for unsupervised transformations).
 |
 |      **fit_params : dict
 |          Additional fit parameters.
 |          Pass only if the estimator accepts additional params in its `fit` method.
 |
 |      Returns
 |      -------
 |      X_new : ndarray array of shape (n_samples, n_features_new)
 |          Transformed array.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  set_output(self, *, transform=None)
 |      Set output container.
 |
 |      See :ref:`sphx_glr_auto_examples_miscellaneous_plot_set_output.py`
 |      for an example on how to use the API.
 |
 |      Parameters
 |      ----------
 |      transform : {"default", "pandas", "polars"}, default=None
 |          Configure output of `transform` and `fit_transform`.
 |
 |          - `"default"`: Default output format of a transformer
 |          - `"pandas"`: DataFrame output
 |          - `"polars"`: Polars output
 |          - `None`: Transform configuration is unchanged
 |
 |          .. versionadded:: 1.4
 |              `"polars"` option was added.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  __init_subclass__(auto_wrap_output_keys=('transform',), **kwargs)
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __dir__(self)
 |      Default dir() implementation.
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters